// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectStoreDotNet.Repository;

#nullable disable

namespace ProjectStoreDotNet.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20221111023118_CorrigirModelSeller")]
    partial class CorrigirModelSeller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectStoreDotNet.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computadores"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Moda"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Livros"
                        });
                });

            modelBuilder.Entity("ProjectStoreDotNet.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("Base_Salary");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birth_Date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 1000.0m,
                            BirthDate = new DateTime(1998, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "bob@gmail.com",
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 3500.0m,
                            BirthDate = new DateTime(1979, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "maria@gmail.com",
                            Name = "Maria Green"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 2200.0m,
                            BirthDate = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "alex@gmail.com",
                            Name = "Alex Grey"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 3000.0m,
                            BirthDate = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "martha@gmail.com",
                            Name = "Martha Red"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 4000.0m,
                            BirthDate = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "donald@gmail.com",
                            Name = "Donald Blue"
                        },
                        new
                        {
                            Id = 6,
                            BaseSalary = 3000.0m,
                            BirthDate = new DateTime(1997, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "bob@gmail.com",
                            Name = "Alex Pink"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
